version: '3.9'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - ./api/.env
    ports:
      - "8000:8000"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    environment:
      - VITE_APP_ID=${VITE_APP_ID:-default-app-id}
      - VITE_API_BASE_URL=http://localhost:8000
    ports:
      - "5173:5173"
    depends_on:
      - api