# Build and (optionally) publish the frontend app

name: App Build

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      - name: Install
        working-directory: app
        run: npm ci
      - name: Test
        working-directory: app
        run: npm run -s lint
      - name: Build
        working-directory: app
        run: npm run -s build

  # Uncomment and configure if you actually publish a package
  # publish-npm:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: actions/setup-node@v4
  #       with:
  #         node-version: 20
  #         registry-url: https://registry.npmjs.org/
  #     - name: Install
  #       working-directory: app
  #       run: npm ci
  #     - name: Publish
  #       working-directory: app
  #       run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.npm_token}}
